language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # install drush
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*
  - phpenv rehash

before_script:
  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database listserv_verify;'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/listserv_verify --enable=simpletest listserv_verify og_purl

  # reference and enable listserv_verify in build site
  - ln -s $(readlink -e $(cd -)) listserv_verify/drupal/sites/all/modules/listserv_verify
  - cd listserv_verify/drupal
  - drush --yes pm-enable listserv_verify

  # Create Drush alias.
  - cd behat
  - composer install --prefer-source

script:
  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  # start a web server on port 8080, run in the background; wait for initialization
  - drush @negawatt runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

  # Run selenium.
  - wget http://selenium-release.storage.googleapis.com/2.40/selenium-server-standalone-2.40.0.jar
  - java -jar selenium-server-standalone-2.40.0.jar -p 4444 &
  - sleep 5

  # Run phantomJs.
  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

  # Run behat tests.
  - cd ../behat
  - ./bin/behat --tags=~@wip

  # Print log ~/phantomjs.log
  - cat ~/phantomjs.log
