<?php

/**
 * Implements hook_menu().
 *
 * @todo Add a unique url for the api
 */
function listserv_verify_menu() {
  $items['listserv-verify/api/verify'] = array(
    'title' => 'Listserv Verify',
    'page callback' => 'listserv_listserv_verify_api_confirm',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Page callback for hook_menu.
 *
 * @todo Possibly check the header to find out where it's coming from.
 */
function listserv_listserv_verify_api_confirm() {
  // If there is no POST data then exit immediately.
  $postdata = file_get_contents("php://input") ? file_get_contents("php://input") : exit;

  // Find the verify keys from the post data.
  $verifykeys = _listserv_find_keys($postdata);
  $verifykeys_count = count($verifykeys);

  if ($verifykeys_count == 1) {
    $status = _listserv_verify_verify_key_status($verifykeys[0]);
    $url = _listserv_verify_find_confirmation_link($postdata);

    if ($status != 'active'){
      echo 'Key Not Active';
    }
    elseif ($status == 'active' && empty($url)) {
      echo 'Link Not Found';
    }
    // Uses HTTPRL to make an asynchronous POST call to the listserv.
    // Use 'print_r(httprl_pr($request))' to investigate the request.
    elseif ($status == 'active' && !empty($url)) {
      $options = array(
        'method' => 'POST',
        'blocking' => FALSE,
      );
      httprl_request($url, $options);
      // Execute requests.
      $request = httprl_send_request();

      // Log the action to watchdog
      watchdog('listserv_verify',
        t('Listserv confirmation link posted to @url after verifying the following key: %key'),
        array('@url' => array_shift($request)->url, '%key' => $verifykeys[0])
      );

      // Set the verify key status to inactive.
      _listserv_verify_change_verify_key_status($verifykeys[0], 'inactive');
      echo 'Confirmed';
    }
  }
  elseif ($verifykeys_count > 1) {
    watchdog('listserv_verify', 'There as more than one verify key in the last message.', array(), WATCHDOG_ERROR, 'link');
  }
  else {
    echo 'Key Not Found';
  }
}

/**
 * Implements hook_mail_alter().
 */
function listserv_verify_mail_alter(&$message) {
  $verifykey = uuid_generate();
  $message['body'][] = '<span class="verifykey">' . $verifykey . '</span>';

  // Create a record of the key and message in the database.
  _listserv_verify_record_new_entry(serialize($message), $verifykey);
}



/**
 * Helper function for saving a new record in the database.
 * @param  $message     The contents of the sent mail.
 * @param  $verifykey   The unique verify key that was generated.
 */
function _listserv_verify_record_new_entry($message, $verifykey = NULL) {
  $record = new stdClass;
  $record->created = REQUEST_TIME;
  $record->message = $message;
  $record->verifykey = $verifykey;

  drupal_write_record('listserv_verify', $record);
}


/**
 * Regexes a blob of text to find the verify key.
 *
 * @param  mixed   $haystack    The blob of text that contains the verify key.
 * @return array   $matches     An array of verify keys found.
 */
function _listserv_find_keys($haystack) {
  $keys = array();

  $subject = is_array($haystack) ? implode(" ", $haystack) : $haystack;
  // This regex pattern can be found in the UUID module.
  $regex = "#[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}#";
  preg_match_all($regex, $subject, $matches);
  // Remove duplicate keys. We are targeting the first instance of the array.
  $keys = array_unique($matches[0]);

  return $keys;
}

/**
 * Regexes a blob of text to find the confirmation link.
 *
 * @param  mixed   $haystack    The blob of text that contains the verify key.
 * @return array   $links       An array of confirmation links found.
 */
function _listserv_verify_find_confirmation_link($haystack) {
  $keys = array();

  $subject = is_array($haystack) ? implode(" ", $haystack) : $haystack;
  $regex = '#http\://lists\.psu\.edu/cgi\-bin/(.*)#';
  preg_match_all($regex, $subject, $matches);
  // Remove duplicate keys.
  $links = array_unique($matches[0]);

  return $links;
}

/**
 * Checks the status of the verify key.
 * @param  string   $key  The Verify Key that we are looking up in the database
 * @return                The status of the verify key. Generally will be either 'active' or 'inactive'
 */
function _listserv_verify_verify_key_status($key) {
  $result = array();

  // Find instances of listserv where the key is the same as $key
  $results = db_select('listserv_verify', 'l')
    ->fields('l')
    ->condition('l.verifykey', $key,'=')
    ->execute();

  foreach ($results as $key => $value) {
    $result[] = $value;
  }

  // We know that there will only be one unique key so we can
  // target the first result.
  if (isset($result[0])) {
    $status = $result[0]->verifykey_status;
    return $status;
  }
}

/**
 * Helper function to change the status of the verify key.
 * @param  $key       The unique verify key.
 * @param  $status    The new status you would like to set the for the key.
 */
function _listserv_verify_change_verify_key_status($key, $status) {
  $result = array();

  // Find instances of listserv where the key is the same as $key
  $results = db_select('listserv_verify', 'l')
    ->fields('l')
    ->condition('l.verifykey', $key,'=')
    ->execute();

  foreach ($results as $key => $record) {
    $record->verifykey_status = $status;
    drupal_write_record('listserv_verify', $record, 'listserv_id');
  }
}
