<?php

/**
 * Implements hook_mail_alter().
 */
function sentmail_mail_alter(&$message) {
  $verifykey = uuid_generate();
  $message['body'][] = '<span style="display:none;" class="verifykey">' . $verifykey . '</span>';

  _sentmail_record_new_entry(serialize($message), $verifykey);
}



/**
 * Helper function for saving a new entity
 * @param  The contents of the sent mail
 */
function _sentmail_record_new_entry($message, $verifykey = NULL) {
  $record = new stdClass;
  $record->created = REQUEST_TIME;
  $record->message = $message;
  $record->verifykey = $verifykey;

  drupal_write_record('sentmail', $record);
}
