<?php

/**
 * Implements hook_menu().
 */
function sentmail_mailgun_menu() {
  $items['sentmail/api/mailgun'] = array(
    'title' => 'Setmail Mailgun Verify',
    'page callback' => 'sentmail_mailgun_json_accept',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function sentmail_mailgun_json_accept() {
  if ($_POST) {
	  variable_set('sentmail_post', $_POST);
  }
  
  $mailgunmessage = variable_get('sentmail_post', 'nothing');
  
  return print_r(kpr($mailgunmessage));
}
